[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["lab/esp32_ble/#"]
  data_format = "json"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "dYg14zE7o-Y2SX5WL3e9cYGSem39aVICbg3PthReWLn6bnxn2JofoflbN-sj-LM7uZEbNXaAWouHkdUQIp_Q8Q==" # Pour générer : load data sur influxdb > API tokens
  organization = "my_lab"
  bucket = "esphome_data"

  # Instance 1 : Capture le BLE
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["lab/esp32_ble/global_scan"]
  data_format = "json"
  name_override = "ble_devices"
  tag_keys = ["name", "address"]

# Instance 2 : Capture le WiFi
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["lab/esp32_ble/wifi_scan"]
  data_format = "json"
  name_override = "wifi_networks"
  tag_keys = ["ssid", "bssid", "auth"]