[agent]
  interval = "10s"
  round_interval = true

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "Zvxr5OJX7dRCqF2rDLrj_CZJs3Zqza2ABccAQyJHX2Li79dlQhecbYLyF7bzIzoMt3VJU05eNh9HICbVT3AGeQ==" # Pour générer : load data sur influxdb > API tokens
  organization = "my_lab"
  bucket = "esphome_data"

# Instance 1 : Capture le BLE
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["lab/esp32_ble/global_scan"]
  data_format = "json"
  name_override = "ble_devices"
  tag_keys = ["name", "address"]

# Instance 2 : Scan WiFi
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["lab/esp32_ble/wifi_scan"]
  data_format = "json"
  name_override = "wifi_scan_results"

# Instance 3 : Sensors (RSSI, etc.) au format JSON
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["lab/esp32_ble/sensor/wifi_rssi_json"]
  data_format = "json"
  name_override = "esp32_sensors"
