[agent]
  interval = "10s"
  round_interval = true

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "Bds70cri5WdmN7UtQXEpHyr0eQuaEmm-05lFn0h-b2qm0ckI8_w9yxpN_ZQmcHP0BBM3d4cJOo_vDMJNUFUEIg==" # Pour générer : load data sur influxdb > API tokens
  organization = "my_lab"
  bucket = "esphome_data"

# Instance 1 : Capture le BLE
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["lab/esp32_ble/global_scan"]
  data_format = "json"
  name_override = "ble_devices"
  tag_keys = ["name", "address"]

# Instance 2 : Capture le WiFi
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["lab/esp32_ble/wifi_scan"]
  data_format = "json"
  name_override = "wifi_networks"

  tag_keys = ["bssid"]
  json_string_fields = ["ssid"]
