#******* Fichier de configuration ESPHome principal*******#

esphome:
  name: esp32_homelab

# Inclusion des secrets
<<: !include secrets.yaml

esp32:
  board: esp32-s3-devkitc-1
  framework: 
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ap_ssid
    password: !secret fallback_ap_password

captive_portal:

# BLE SCAN GLOBAL
esp32_ble_tracker:
  scan_parameters:
    active: true
    interval: 320ms
    window: 300ms

  on_ble_advertise:
    then:
      - lambda: |- # Scan global console
          std::string name = x.get_name();
          if (name.empty()) {
            name = "Inconnu";
          }
          ESP_LOGI("BLE_SCAN", "[%-15s] RSSI: %d dBm | Adr: %s", 
                   name.c_str(), 
                   x.get_rssi(), 
                   x.address_str().c_str());
      - mqtt.publish: # Scan global Grafana
          topic: "lab/esp32_ble/global_scan"
          payload: !lambda |-
            return "{\"name\": \"" + x.get_name() + "\", \"address\": \"" + x.address_str() + "\", \"rssi\": " + std::to_string(x.get_rssi()) + "}";

# Communication MQTT vers le serveur Docker
mqtt:
  broker: !secret mqtt_broker_ip
  topic_prefix: lab/esp32_ble

# Sensor RSSI pour données Grafana
sensor:
  - platform: ble_rssi
    mac_address: A0:7D:9C:8B:C0:29  # MAC tel personnel
    name: "Signal_Tel_Lab"
    filters:
      - median:
          window_size: 7
          send_every: 4

# Includes BLE
<<: !include ble/ble_tracker.yaml
<<: !include ble/ble_presence.yaml
<<: !include ble/ble_rssi.yaml